# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Peer_Review03' do
pod ‘CurrencyRequest’
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Peer_Review03

end
